name: cosmos
description: A sample command-line application.
version: 0.1.0

environment:
  sdk: '>=2.8.0 <3.0.0'

dependencies:
  dio: ^3.0.9
  dotenv: ^2.0.0

dev_dependencies:
  test: ^1.15.2
  test_coverage: ^0.4.3